In [8]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

In [14]:
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df
#AI建立一個function
#依據df
#建立一個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高分', '最低分','中間值']

df

科目    國文  英文   數學  自然   社會   總分    平均    排名
學生
學生1   94  82   91  53   76  396  79.2  10.0
學生2   86  75   50  56   85  352  70.4  36.0
學生3   86  56   81  82   71  376  75.2  25.0
學生4   54  75   65  85   66  345  69.0  38.0
學生5   56  92   73  82   95  398  79.6   9.0
學生6   88  86   82  77   76  409  81.8   7.0
學生7   50  58   81  93   54  336  67.2  42.0
學生8   59  86   62  59   66  332  66.4  44.0
學生9   85  60  100  59   86  390  78.0  15.0
學生10  77  97   71  68   78  391  78.2  13.0
學生11  75  79   71  96   59  380  76.0  22.0
學生12  67  85   58  70   70  350  70.0  37.0
學生13  58  61   99  57   97  372  74.4  27.0
學生14  77  73   98  88   77  413  82.6   6.0
學生15  63  88   51  93   92  387  77.4  16.0
學生16  98  65   82  81   56  382  76.4  20.0
學生17  88  57   62  60   63  330  66.0  46.0
學生18  87  84   97  65   74  407  81.4   8.0
學生19  57  60   70  71   50  308  61.6  48.0
學生20  66  65   66  67   72  336  67.2  42.0
學生21  50  53   60  82   98  343  68.6  39.0
學生22  78  99   80  67   93  417  83.4   5.0
學生23  75  71   83  52   84  365  73.0  33.0
學生24  51  65   66  61   53  296  59.2  50.0
學生25  58  77   71  76   57  339  67.8  41.0
學生26  70  64   67  67   75  343  68.6  39.0
學生27  59  64   90  83   99  395  79.0  11.0
學生28  77  58   99  64   86  384  76.8  19.0
學生29  62  94   97  90   51  394  78.8  12.0
學生30  53  51   79  73   76  332  66.4  44.0
學生31  65  66   57  60   53  301  60.2  49.0
學生32  70  91   86  88   88  423  84.6   2.0
學生33  86  86   51  69   77  369  73.8  32.0
學生34  68  60   68  99   86  381  76.2  21.0
學生35  87  83   71  66   64  371  74.2  29.0
學生36  62  86   69  82   86  385  77.0  17.0
學生37  53  73   95  99  100  420  84.0   3.0
學生38  68  65   73  96   63  365  73.0  33.0
學生39  79  60   81  50   58  328  65.6  47.0
學生40  60  83   90  92   50  375  75.0  26.0
學生41  82  58   71  97   54  362  72.4  35.0
學生42  65  90   78  50   97  380  76.0  22.0
學生43  96  73   64  83   54  370  74.0  30.0
學生44  88  92   96  87   61  424  84.8   1.0
學生45  58  96   67  74   96  391  78.2  13.0
學生46  59  60   97  96   73  385  77.0  17.0
學生47  50  67   92  62   99  370  74.0  30.0
學生48  90  95   64  82   87  418  83.6   4.0
學生49  80  78   70  73   79  380  76.0  22.0
學生50  91  53   79  70   79  372  74.4  27.0

In [15]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

科目      國文    英文      數學     自然      社會
平均   71.22  73.9   76.42  75.04   74.78
最高   98.00  99.0  100.00  99.00  100.00
最低   50.00  51.0   50.00  50.00   50.00
中間值  69.00  73.0   73.00  73.50   76.00