In [1]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文   英文   數學   自然   社會   總分    平均    排名
學生
學生1   57   66   93   64   99  379  75.8  22.0
學生2   52   86  100   50   93  381  76.2  21.0
學生3   85   89   54   85   70  383  76.6  18.0
學生4   74   79   57   87   72  369  73.8  28.0
學生5   61   80   67   76   75  359  71.8  36.0
學生6   80  100   58   60   52  350  70.0  39.0
學生7   76   81   91   78   57  383  76.6  18.0
學生8   66   70   94   59   84  373  74.6  25.0
學生9   83   87   93   96   68  427  85.4   5.0
學生10  56   82   78   63   63  342  68.4  42.0
學生11  94   61   73   78   55  361  72.2  35.0
學生12  79   79   92   51   97  398  79.6  11.0
學生13  51   82   91   62   55  341  68.2  44.0
學生14  64   76   99   55   70  364  72.8  31.0
學生15  55   50   87   56   70  318  63.6  48.0
學生16  61   59   77   51   59  307  61.4  49.0
學生17  62   93   51   58   86  350  70.0  39.0
學生18  98   59   52   62   51  322  64.4  47.0
學生19  82   82  100   84   81  429  85.8   4.0
學生20  68   92   61   66   84  371  74.2  26.0
學生21  87  100   93   71   91  442  88.4   2.0
學生22  79   59   75   82   94  389  77.8  17.0
學生23  55   68   90   66   87  366  73.2  29.0
學生24  66   70   87   56   71  350  70.0  39.0
學生25  63   67   98   95   71  394  78.8  13.0
學生26  97   95   91   78  100  461  92.2   1.0
學生27  87   92   66   94   60  399  79.8   9.0
學生28  82   93  100   58   62  395  79.0  12.0
學生29  65   95   92   95   80  427  85.4   5.0
學生30  83   64   83   77   56  363  72.6  33.0
學生31  75   72   67   99   69  382  76.4  20.0
學生32  94   96   55   59   90  394  78.8  13.0
學生33  63   82   55   62   93  355  71.0  37.0
學生34  84   62   56   59   92  353  70.6  38.0
學生35  67   98   85  100   83  433  86.6   3.0
學生36  69   53   91   72   50  335  67.0  46.0
學生37  94   56   62   73   57  342  68.4  42.0
學生38  89   63   77   89   90  408  81.6   8.0
學生39  59   75   62   91   76  363  72.6  33.0
學生40  81   56   91   77   71  376  75.2  24.0
學生41  55   73   91   69   51  339  67.8  45.0
學生42  83   61   82   69   76  371  74.2  26.0
學生43  68   95   85   65   51  364  72.8  31.0
學生44  56   96   76   85   86  399  79.8   9.0
學生45  98   76   86   65   85  410  82.0   7.0
學生46  54   51   66   50   56  277  55.4  50.0
學生47  66   70   60  100   69  365  73.0  30.0
學生48  92   84   87   60   67  390  78.0  16.0
學生49  90   62   88   89   65  394  78.8  13.0
學生50  70   57   88   66   96  377  75.4  23.0

In [2]:
#選擇欄位
df1 = df[['國文','英文','數學','自然','社會']]
df1

科目    國文   英文   數學   自然   社會
學生
學生1   57   66   93   64   99
學生2   52   86  100   50   93
學生3   85   89   54   85   70
學生4   74   79   57   87   72
學生5   61   80   67   76   75
學生6   80  100   58   60   52
學生7   76   81   91   78   57
學生8   66   70   94   59   84
學生9   83   87   93   96   68
學生10  56   82   78   63   63
學生11  94   61   73   78   55
學生12  79   79   92   51   97
學生13  51   82   91   62   55
學生14  64   76   99   55   70
學生15  55   50   87   56   70
學生16  61   59   77   51   59
學生17  62   93   51   58   86
學生18  98   59   52   62   51
學生19  82   82  100   84   81
學生20  68   92   61   66   84
學生21  87  100   93   71   91
學生22  79   59   75   82   94
學生23  55   68   90   66   87
學生24  66   70   87   56   71
學生25  63   67   98   95   71
學生26  97   95   91   78  100
學生27  87   92   66   94   60
學生28  82   93  100   58   62
學生29  65   95   92   95   80
學生30  83   64   83   77   56
學生31  75   72   67   99   69
學生32  94   96   55   59   90
學生33  63   82   55   62   93
學生34  84   62   56   59   92
學生35  67   98   85  100   83
學生36  69   53   91   72   50
學生37  94   56   62   73   57
學生38  89   63   77   89   90
學生39  59   75   62   91   76
學生40  81   56   91   77   71
學生41  55   73   91   69   51
學生42  83   61   82   69   76
學生43  68   95   85   65   51
學生44  56   96   76   85   86
學生45  98   76   86   65   85
學生46  54   51   66   50   56
學生47  66   70   60  100   69
學生48  92   84   87   60   67
學生49  90   62   88   89   65
學生50  70   57   88   66   96

In [ ]:
s = df1.loc['學生1']  #選擇學生1的成績
#取出成績小於60的科目
less_than_60_series = s[s < 60] 

#取出不及格的科目
less_than_60_subjects = less_than_60_series.index.tolist()
less_than_60_subjects

#取出不及格科目的成績
less_than_60_scores = less_than_60_series.values.tolist()
less_than_60_scores

#建立一個Series,值要轉換成字串,如果有多個值則用逗號分隔
less_than_60_scores_str = ','.join(map(str, less_than_60_scores))
less_than_60_subjects_str = ','.join(less_than_60_subjects)
pd.Series([less_than_60_scores_str, less_than_60_subjects_str], index=['分數', '不及格科目'])

分數       57
不及格科目    國文
dtype: object

In [20]:
def apply_statistics(s):
    #取出成績小於60的科目
    less_than_60_series = s[s < 60] 
    #不及格科目數量
    less_than_60_subjects_count = less_than_60_series.count()
    
    #取出不及格的科目
    less_than_60_subjects = less_than_60_series.index.tolist()
    
    #取出不及格科目的成績
    less_than_60_scores = less_than_60_series.values.tolist()
    
    #建立一個Series,值要轉換成字串,如果有多個值則用逗號分隔
    less_than_60_scores_str = ','.join(map(str, less_than_60_scores))
    less_than_60_subjects_str = ','.join(less_than_60_subjects)
    return pd.Series([less_than_60_subjects_count,less_than_60_subjects_str, less_than_60_scores_str], index=['不及格科目數量','不及格科目', '分數'])

    
df2 = df1.apply(apply_statistics,axis=1)
df2

      不及格科目數量        不及格科目           分數
學生
學生1         1           國文           57
學生2         2        國文,自然        52,50
學生3         1           數學           54
學生4         1           數學           57
學生5         0
學生6         2        數學,社會        58,52
學生7         1           社會           57
學生8         1           自然           59
學生9         0
學生10        1           國文           56
學生11        1           社會           55
學生12        1           自然           51
學生13        2        國文,社會        51,55
學生14        1           自然           55
學生15        3     國文,英文,自然     55,50,56
學生16        3     英文,自然,社會     59,51,59
學生17        2        數學,自然        51,58
學生18        3     英文,數學,社會     59,52,51
學生19        0
學生20        0
學生21        0
學生22        1           英文           59
學生23        1           國文           55
學生24        1           自然           56
學生25        0
學生26        0
學生27        0
學生28        1           自然           58
學生29        0
學生30        1           社會           56
學生31        0
學生32        2        數學,自然        55,59
學生33        1           數學           55
學生34        2        數學,自然        56,59
學生35        0
學生36        2        英文,社會        53,50
學生37        2        英文,社會        56,57
學生38        0
學生39        1           國文           59
學生40        1           英文           56
學生41        2        國文,社會        55,51
學生42        0
學生43        1           社會           51
學生44        1           國文           56
學生45        0
學生46        4  國文,英文,自然,社會  54,51,50,56
學生47        0
學生48        0
學生49        0
學生50        1           英文           57

In [21]:
#df要和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

,國文,英文,數學,自然,社會,總分,平均,排名,不及格科目數量,不及格科目,分數
學生,,,,,,,,,,,
學生1,57,66,93,64,99,379,75.8,22.0,1,國文,57
學生2,52,86,100,50,93,381,76.2,21.0,2,"國文,自然","52,50"
學生3,85,89,54,85,70,383,76.6,18.0,1,數學,54
學生4,74,79,57,87,72,369,73.8,28.0,1,數學,57
學生5,61,80,67,76,75,359,71.8,36.0,0,,
學生6,80,100,58,60,52,350,70.0,39.0,2,"數學,社會","58,52"
學生7,76,81,91,78,57,383,76.6,18.0,1,社會,57
學生8,66,70,94,59,84,373,74.6,25.0,1,自然,59
學生9,83,87,93,96,68,427,85.4,5.0,0,,
學生10,56,82,78,63,63,342,68.4,42.0,1,國文,56
學生11,94,61,73,78,55,361,72.2,35.0,1,社會,55
學生12,79,79,92,51,97,398,79.6,11.0,1,自然,51
學生13,51,82,91,62,55,341,68.2,44.0,2,"國文,社會","51,55"
學生14,64,76,99,55,70,364,72.8,31.0,1,自然,55
學生15,55,50,87,56,70,318,63.6,48.0,3,"國文,英文,自然","55,50,56"
學生16,61,59,77,51,59,307,61.4,49.0,3,"英文,自然,社會","59,51,59"
學生17,62,93,51,58,86,350,70.0,39.0,2,"數學,自然","51,58"
學生18,98,59,52,62,51,322,64.4,47.0,3,"英文,數學,社會","59,52,51"
學生19,82,82,100,84,81,429,85.8,4.0,0,,
學生20,68,92,61,66,84,371,74.2,26.0,0,,
學生21,87,100,93,71,91,442,88.4,2.0,0,,
學生22,79,59,75,82,94,389,77.8,17.0,1,英文,59
學生23,55,68,90,66,87,366,73.2,29.0,1,國文,55
學生24,66,70,87,56,71,350,70.0,39.0,1,自然,56
學生25,63,67,98,95,71,394,78.8,13.0,0,,
學生26,97,95,91,78,100,461,92.2,1.0,0,,
學生27,87,92,66,94,60,399,79.8,9.0,0,,
學生28,82,93,100,58,62,395,79.0,12.0,1,自然,58
學生29,65,95,92,95,80,427,85.4,5.0,0,,
學生30,83,64,83,77,56,363,72.6,33.0,1,社會,56
學生31,75,72,67,99,69,382,76.4,20.0,0,,
學生32,94,96,55,59,90,394,78.8,13.0,2,"數學,自然","55,59"
學生33,63,82,55,62,93,355,71.0,37.0,1,數學,55
學生34,84,62,56,59,92,353,70.6,38.0,2,"數學,自然","56,59"
學生35,67,98,85,100,83,433,86.6,3.0,0,,
學生36,69,53,91,72,50,335,67.0,46.0,2,"英文,社會","53,50"
學生37,94,56,62,73,57,342,68.4,42.0,2,"英文,社會","56,57"
學生38,89,63,77,89,90,408,81.6,8.0,0,,
學生39,59,75,62,91,76,363,72.6,33.0,1,國文,59
學生40,81,56,91,77,71,376,75.2,24.0,1,英文,56
學生41,55,73,91,69,51,339,67.8,45.0,2,"國文,社會","55,51"
學生42,83,61,82,69,76,371,74.2,26.0,0,,
學生43,68,95,85,65,51,364,72.8,31.0,1,社會,51
學生44,56,96,76,85,86,399,79.8,9.0,1,國文,56
學生45,98,76,86,65,85,410,82.0,7.0,0,,
學生46,54,51,66,50,56,277,55.4,50.0,4,"國文,英文,自然,社會","54,51,50,56"
學生47,66,70,60,100,69,365,73.0,30.0,0,,
學生48,92,84,87,60,67,390,78.0,16.0,0,,
學生49,90,62,88,89,65,394,78.8,13.0,0,,
學生50,70,57,88,66,96,377,75.4,23.0,1,英文,57

In [22]:
#df_merged請儲存為excel檔
df_merged.to_excel('students_scores.xlsx', index=True)